services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Jedi
      MARIADB_DATABASE: Horror_404
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mariadb

volumes:
  mariadb_data:
